pageinfo = [[1200956539,1447],
	[1200958092,828],
	[1200932268,1071],
	[1200932313,742],
	[1200956470,1893],
	[1200943468,1463],
	[1200944551,853],
	[1200943935,1402],
	[1200946217,2661],
	[1200947307,1331],
	[1200946624,1784],
	[1200932055,1237],
	[1200946875,1050],
	[1200940175,2631],
	[1200930911,2726],
	[1200932290,1729],
	[1200957863,2571],
	[1200942523,1253],
	[1200941848,1228],
	[1200941492,1319],
	[1200941237,887],
	[1200942587,901],
	[1200942392,1592],
	[1200939703,963]];
pagedata = [ ["../author_info/about.html","About Author","About the Author Hello! My name is Sam Gleske. I am 21 years old and do JavaScript programming as a hobby. I am a Computer Engineering student at ...",""],
["../author_info/contact.html","Contact","Contact the Author Sam Gleske http://www.pages.drexel.edu/~sag47/ ",""],
["../author_info/develop.html","Other Developments","Other Developments By Sam Gleske Base64 Encrypt/Decrypt Plugin for IE (not released) (completed) Initial helped develop Pioneer Linux . FolderView...",""],
["../author_info/resume.html","Resume","Resume Request If you would like to see my resume then you must request it because I don&#39;t post it online. You can simply email me (my email is in...",""],
["../author_info/tech.html","Technologies used","Technologies This section discusses the technologies that were used to create the calculator and this help system. First of all, the web languages...",""],
["../button_help/about_btns.html","Overview","About Buttons This section is to teach you how to use the different buttons of the Scientific Calculator.You will learn the names of the function ...",""],
["../button_help/basic_eqtns.html","Basic Equations","Basic Equation Buttons Above are the basic calculator buttons found on every calculator. Rules: There has to be a symbol in between any two algebr...",""],
["../button_help/del_btn.html","Deletion Buttons","Deletion Buttons There are several ways to remove variables or entire equations from the display or memory of the Scientific Calculator. The indic...",""],
["../button_help/mem_fxn.html","Memory Buttons","Memory Buttons In this help topic you will learn how to use the memory functions of the Scientific Calculator. At the top you should recognize the...",""],
["../button_help/misc.html","Miscellaneous","Miscellaneous The rest of the button functions of the Scientific Calculator fall into this category.After you read this you will be scott free and...",""],
["../button_help/pow.html","Power Functions","Power Functions Now we discuss power functions.Look at the picture below for a list of the power function buttons: The first power function we sha...",""],
["../button_help/shortcuts.html","Button Shortcuts","Button Shortcuts All the Basic Equation Keys work MC press C key MR press R key MS press S key M+ press M key pi press P key () press () keys comm...",""],
["../button_help/trig.html","Trigonometric Functions","Trigonometric Functions exp and ln are inverse of each other meaning exp ln =1 exp (exponential) takes the exponential of the current equation ln ...",""],
["../calc_info.html","Calc Info","About What is the Scientific Calculator v1.2.4? It is an advanced calculator that uses JavaScript (not Java) to compute advanced math functions.Ty...",""],
["../compatible_browsers.html","Compatible Browsers","Compatible Browsers Scientific Calculator v1.2.4 is compatible with the following web browsers on all platforms: Internet Explorer 6.0+ Firefox 1....",""],
["../license/disclaimer.html","Disclaimer","Warning! I do my best to make sure all the calculations and conversions are accurate and correct. But there is always the possibility that they ar...",""],
["../license/license.html","License","License Copyright &#169; 2005 Sam Gleske Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated d...",""],
["../menu_help/about_menu.html","About Menu","About Menu What is the menu? What is a submenu? A submenu is a branch within the main headers of the menu. Click on the main header File. You will...",""],
["../menu_help/conv_menu.html","Conv Menu","Conv Menu Header What is the Conv Menu? What does Conv mean? Conv is abbreviated for Convert. It&#39;s purpose is to convert between number types Func...",""],
["../menu_help/edit_menu.html","Edit Menu","Edit Menu Header What is the Edit Menu? Functions of the Edit Menu: Edit &#62; Copy Copies the diplayed equation Edit &#62; Paste Pastes contents of clipb...",""],
["../menu_help/file_menu.html","File Menu","File Menu Header What is the File Menu? Functions of the File Menu: Under File &#62; Reload: This submenu resets all settings of the calculator Under ...",""],
["../menu_help/help_menu.html","Help Menu","Help Menu Header What is the Help Menu? Functions of the Help Menu: Help &#62; Help Displays the help database (this entire help guide). Help &#62; About ...",""],
["../menu_help/settings_menu.html","Settings Menu","Settings Menu Header What is the Settings Menu? What does the Settings Menu do? Adjusts different settings of the calculator so the user can simpl...",""],
["../welcome.html","Welcome","Welcome Welcome to the Scientific Calculator v1.2.4 Help Database. Here you will find extensive knowledge and expertise with the function of this ...",""]];
